feat(joml): align Region related classes
Terasology/StructureTemplates pull request #46
Opened 2020-11-04 23:04 UTC by jdrueckert

- needs to be merged with https://github.com/Terasology/Scenario/pull/48

2020-11-06 04:27 UTC, pollend requested changes

2020-11-06 04:27 UTC, pollend commented on src/main/java/org/terasology/structureTemplates/util/ProtectedRegionUtility.java
> +import org.terasology.world.block.BlockRegion;
```suggestion
import org.terasology.entitySystem.entity.EntityRef;
import org.terasology.math.JomlUtil;
import org.terasology.math.geom.Vector3i;
import org.terasology.structureTemplates.components.ProtectedRegionsComponent;
import org.terasology.world.block.BlockRegion;
```

2020-11-10 21:23 UTC, jdrueckert commented
@pollend can be re-reviewed

2020-11-19 22:36 UTC, jdrueckert commented
@pollend this still needs a review, so that we can get https://github.com/Terasology/Scenario/pull/48 in

2020-11-21 19:53 UTC, pollend commented on src/main/java/org/terasology/structureTemplates/util/ProtectedRegionUtility.java
> +                    if (region.containsPoint(JomlUtil.from(position))) {
BlockRegion also has a containsBlock function that is non inclusive. double check with encompasses to make sure the implementation is correct.

2020-12-31 11:36 UTC, jdrueckert commented
Changes already done

2020-12-31 11:36 UTC, closed without merging